# Generated by Django 4.0.6 on 2022-08-02 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC_ETH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(choices=[('BTC', 'KRW-BTC'), ('ETH', 'KRW-ETH')], default='KRW-BTC', max_length=10)),
                ('OpenPrice', models.FloatField(default=-1, null=True)),
                ('MA15', models.FloatField(default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='거래',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(default='no-ticker', max_length=10)),
                ('BuyPrice', models.FloatField(default=-1, null=True)),
                ('SoldPrice', models.FloatField(default=-1, null=True)),
                ('BuyTime', models.TimeField(auto_now_add=True, null=True)),
                ('SoldTime', models.TimeField(auto_now_add=True, null=True)),
                ('IsDummy', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='날짜',
            fields=[
                ('ID', models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True)),
                ('Date_Start', models.DateTimeField(auto_now_add=True, unique=True)),
                ('Date_End', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='날짜',
            index=models.Index(fields=['ID'], name='날짜_Index'),
        ),
        migrations.AddField(
            model_name='거래',
            name='날짜_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchData.날짜'),
        ),
        migrations.AddField(
            model_name='btc_eth',
            name='날짜_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchData.날짜'),
        ),
        migrations.AddIndex(
            model_name='거래',
            index=models.Index(fields=['날짜_ID', 'Ticker'], name='거래_Index'),
        ),
        migrations.AddConstraint(
            model_name='거래',
            constraint=models.UniqueConstraint(fields=('날짜_ID', 'Ticker'), name='거래_PK'),
        ),
        migrations.AddIndex(
            model_name='btc_eth',
            index=models.Index(fields=['날짜_ID', 'Ticker'], name='BTC_ETH_Index'),
        ),
        migrations.AddConstraint(
            model_name='btc_eth',
            constraint=models.UniqueConstraint(fields=('날짜_ID', 'Ticker'), name='BTC_ETH_PK'),
        ),
    ]
